//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Sprites/Pirates/14-TileSets/Map1.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// LDtk Enum for Map1
/// </summary>
public enum EnemyType
{
    Null,
    Pig,
    PigPetrol
}

/// <summary>
/// LDtk Enum for Map1
/// </summary>
public enum LevelChange
{
    Null,
    Start,
    Finish
}

/// <summary>
/// LDtk Enum for Map1
/// </summary>
public enum CollectibleType
{
    Null,
    Diamond,
    Heart
}